import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Box, Separator } from "@chakra-ui/react";
import { themeTokens } from "@/theme/tokens";

import { CartProvider } from "@/components/cart/cart-provider";
import { CartSidebar } from "@/components/cart/cart-sidebar";
import { hasArticlesContent } from "@/data/loaders/articles";
import { getBrandData } from "@/data/brand";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hasArticles = await hasArticlesContent();
  const brand = await getBrandData();

  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable}`}
      >
        <Provider>
          <Box maxW={themeTokens.layoutWidth} mx="auto" w="full">
            <CartProvider>
              <Header hasArticles={hasArticles} brand={brand} />
              <Separator />
              {children}
              <Separator />
              <Footer brand={brand} />
              <CartSidebar />
            </CartProvider>
          </Box>
        </Provider>
      </body>
    </html>
  );
}
